name: pass_report
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.11  # Or your desired Python version
  - pandas
  - matplotlib
  - polars-lts-cpu  # nflreadpy default
  - openpyxl
  - jupyter
  - tableau
  - pip
  
  # Pip packages
  - pip:
    - nflreadpy
